name: instagram
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.1"

dependencies:
  # HELPER
  equatable: ^2.0.3
  logger: ^1.1.0
  http: ^0.13.4
  shared_preferences: ^2.0.11
  get_it: ^7.2.0
  intl: ^0.17.0

  # WIDGET
  bot_toast: ^4.0.1
  flutter_dialogs: ^2.1.1

  # STATE MANAGEMENT
  flutter_bloc: ^8.0.0



  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  video_player: ^2.4.2
  auto_route: ^4.0.1
  internet_connection_checker: ^0.0.1+4
  flutter_easyloading: ^3.0.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^4.0.0
  test: ^1.19.5

  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/fonts/
  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Black.otf
          weight: 900
